# Эти группы настроек и настройки будут созданы, если отсутствуют.
# Для этого нужно зайти в раздел "настройки" в админке.

base:
  title: Общее
  items:
    htmlHeadPrefix:
      title: HTML в начале <head>
      value: <!-- html head prefix -->
    htmlHeadSuffix:
      title: HTML в конце <head>
      value: <!-- html head suffix -->
    htmlBodyPrefix:
      title: HTML в начале <body>
      value: <!-- html body prefix -->
    htmlBodySuffix:
      title: HTML в конце <body>
      value: <!-- html body suffix -->
    pageTitlePrefix:
      title: Заголовок страницы: префикс
    pageTitleSuffix:
      title: Заголовок страницы: суффикс
